name: Test link to GADI
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        ### Latest at time of writing
        uses: actions/checkout@v3.3.0
      - name: Sync repository to Gadi
        ### Latest at time of writing
        uses: up9cloud/action-rsync@v1.3
        env:
          HOST: gadi.nci.org.au
          TARGET: ${{secrets.GADI_REPO_PATH}}
          KEY: ${{secrets.DEPLOY_KEY}}
          USER: ${{secrets.GADI_USER}}
      - name: Create Admin dirs on Gadi
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: gadi.nci.org.au
          username: ${{secrets.GADI_USER}}
          key: ${{secrets.DEPLOY_KEY}}
          script: |
            source ${{secrets.GADI_REPO_PATH}}/scripts/install_config.sh
            source ${{secrets.GADI_REPO_PATH}}/scripts/functions.sh
            mkdir -p $ADMIN_DIR $JOB_LOG_DIR $BUILD_STAGE_DIR
            set_admin_perms $ADMIN_DIR $JOB_LOG_DIR $BUILD_STAGE_DIR
