name: "Test scheduled action to GADI"
on:
  schedule:
  - cron: "10 23 0 0 0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        ### Latest at time of writing
        uses: actions/checkout@v3.3.0
      - name: Create Admin dirs on Gadi
        uses: appleboy/ssh-action@v0.1.7
        with:
          debug: True
          host: gadi.nci.org.au
          username: ${{ secrets.GADI_USER }}
          key: ${{ secrets.GADI_KEY }}
          passphrase: ${{ secrets.GADI_KEY_PASSPHRASE }}
          script: |
            cd /home/565/mb0427/MonashWeb/
            mkdir -p TEST_FROM_GITHUB
            qsub -N GITHUB_test -P w40 -q normal -l ncpus=1 -l walltime=00:05:00 -l wd -l storage=gdata/rt52 -l mem=8GB -M michael.barnes@monash.edu -m abe
