name: Test link to GADI
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "$(date +'%Y-%m-%d %H:%M:%S')"
      - name: Checkout repository
        ### Latest at time of writing
        uses: actions/checkout@v3.3.0
      - name: Create Admin dirs on Gadi
        uses: appleboy/ssh-action@v0.1.7
        with:
          debug: True
          host: gadi.nci.org.au
          username: ${{ secrets.GADI_USER }}
          key: ${{ secrets.GADI_KEY }}
          passphrase: ${{ secrets.GADI_KEY_PASSPHRASE }}
          script: |
            cd /home/565/mb0427/MonashWeb/monash_weather_web/
            ./download_files.sh
            qsub submit.PBS
            ./reorganise_files.sh
