name: Test link to GADI
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        ### Latest at time of writing
        uses: actions/checkout@v3.3.0
      - name: Create Admin dirs on Gadi
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: gadi.nci.org.au
          username: ${{ secrets.GADI_USER }}
          key: ${{ secrets.GADI_KEY }}
          passphrase: ${{ secrets.GADI_KEY_PASSPHRASE }}
          script: |
            mkdir -p "\home\565\mb0427\MonashWeb\TEST"
